sudo: false
language: objective-c

before_install:
  - npm install
  - bundle

script:
  - echo "Compiling tests"
  - make compile-test
  - make run-test
  - make run-test
  - make run-test
  - make run-test
  - make run-test
  - make run-test
  - make run-test
  - make run-test
  - make run-test

after_failure:
  - echo "Waiting 5 seconds for crash reports..."
  - sleep 5
  - echo "Reported Crashes:"
  - make show-crash

after_success:
  - make slather
