sudo: false
language: objective-c
xcode_project: paq.xcodeproj # path to your xcodeproj folder
xcode_scheme: paq-tests
xcode_sdk: macosx

before_install:
  - npm install
  - bundle

script:
  - make test

after_success:
  - make submit-coverage
