sudo: false
language: objective-c

before_install:
  - npm install
  - gem i slather --no-ri --no-rdoc
  - ulimit -c unlimited -S

script:
  - echo "Compiling tests"
  - make compile-test
  - echo "Test run #1"
  - make run-test
  - echo "Test run #2"
  - make run-test
  - echo "Test run #3"
  - make run-test
  - echo "Test run #4"
  - make run-test
  - echo "Test run #5"
  - make run-test
  - echo "Test run #6"
  - make run-test
  - echo "Test run #7"
  - make run-test
  - echo "Test run #8"
  - make run-test
  - echo "Test run #9"
  - make run-test
  - echo "Test run #10"
  - make run-test

after_failure:
  - echo "Waiting 5 seconds for crash reports..."
  - sleep 5
  - echo "Reported Crashes:"
  - make show-crash

after_success:
  - make slather
