sudo: false
language: objective-c
xcode_project: paq.xcodeproj # path to your xcodeproj folder
xcode_scheme: paq-tests
xcode_sdk: macosx

before_install:
  - npm install
  - xctool -scheme 'paq-tests' CONFIGURATION_BUILD_DIR=$HOME

script:
  - $HOME/paq-tests --success --durations yes --warn NoAssertions

