sudo: false
language: objective-c

before_install:
  - npm install
  - gem i slather --no-ri --no-rdoc
  - ulimit -c unlimited -S

script:
  - RESULT=1 make test & pid=$! && fg;
  - if [[ ${RESULT} != 0 ]]; then lldb --core /cores/core.$pid --batch --one-line "bt" ; fi;
  - if [[ ${RESULT} != 0 ]]; then exit $RESULT ; fi;

after_success:
  - make slather
