sudo: false
language: objective-c

before_install:
  - npm install
  - gem i slather --no-ri --no-rdoc
  - ulimit -c unlimited -S

script:
  - make test

after_failure:
  - echo "Sleeping for crash report..."
  - sleep 5
  - make show-crash

after_success:
  - make slather
