sudo: false
language: objective-c
xcode_project: paq.xcodeproj
xcode_scheme: paq-tests
xcode_sdk: macosx

before_install:
  - npm install
  - sudo easy_install cpp-coveralls
  - brew uninstall xctool
  - brew update
  - brew install xctool --HEAD

script:
  - make test

after_success:
  - ./scripts/coveralls.sh